options:
    repository:
        type: string
        default: "https://github.com/AdamIsrael/openvim.git"
        description: "The Git repository to install OpenVIM from."
    branch:
        type: string
        default: "master"
        description: "The Git branch to checkout"
    mode:
        type: string
        default: "development"
        description: "The mode to run OpenVIM in. [normal, test, host only, development]"
